#!/bin/zsh

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

gnome-keyring-daemon --start --components=pkcs11 &

# Start anacron using $HOME/.anacron as cron job storage (symlinked to dotfiles)
/usr/sbin/anacron -d -t $HOME/.anacron/etc/anacrontab -S $HOME/.anacron/spool &> $HOME/.anacron/anacron.log &

# Done here
touch /tmp/sway-started
