#!/bin/zsh

[[ ! $(ps a | grep gnome-keyring-daemon) ]] && gnome-keyring-daemon --start --components=pkcs11 &
[[ ! $(ps a | grep polkit) ]] && /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# environment
export QT_QPA_PLATFORM=wayland
export DOTNET_CLI_TELEMETRY_OPTOUT=1

