#!/bin/sh
# ~/.xprofile

# sourced at boot by both xinit and most display managers like lightdm

export XDG_CONFIG_HOME="$HOME/.config"

[ -d /sbin ] && PATH="$PATH:/sbin"
[ -d /usr/sbin ] && PATH="$PATH:/usr/sbin"
[ -d "$HOME/bin" ] && PATH="$HOME/bin:$PATH"
PATH="$HOME/bin/crosstools-ng/bin/:$PATH"

# keyring and polkit daemons
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
gnome-keyring-daemon --start --components=pkcs11 &

# pressing super alone simulates Alt-F1
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# display timeout and sleep
xset s 1200 1300
xset dpms 1200 1300 1400

# keyboard repeat rate
xset r rate 280 43

setxkbmap gb

#enable tap click on touchpad
xinput set-prop 11 296 1
