"type" = "blue"
"constant" = "purple"
"constant.builtin" = "blue"
"constant.builtin.boolean" = "purple"
"constant.numeric" = "purple"
"constant.character.escape" = "orange"
"string" = "yellow"
"string.regexp" = "red"
"string.special" = "red"
"comment" = "grey"
"variable" = "orange"
"variable.builtin" = "blue"
"variable.parameter" = "orange"
"variable.other.member" = "orange"
"label" = "red"
"punctuation" = "grey"
"punctuation.special" = "grey"
"keyword" = { fg = "red", modifiers = ["bold"] }
"operator" = "red"
"function" = "green"
"function.builtin" = "blue"
"function.macro" = "green"
"tag" = "red"
"namespace" = "blue"
"attribute" = "purple"
"constructor" = "blue"
"module" = "blue"
"special" = "red"

"markup.heading.marker" = "grey"
"markup.heading.1" = { fg = "red", modifiers = ["bold"] }
"markup.heading.2" = { fg = "orange", modifiers = ["bold"] }
"markup.heading.3" = { fg = "yellow", modifiers = ["bold"] }
"markup.heading.4" = { fg = "green", modifiers = ["bold"] }
"markup.heading.5" = { fg = "blue", modifiers = ["bold"] }
"markup.heading.6" = { fg = "fg", modifiers = ["bold"] }
"markup.list" = "red"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "blue", modifiers = ["underlined"] }
"markup.link.text" = "purple"
"markup.quote" = "grey"
"markup.raw" = "green"

"diff.plus" = "green"
"diff.delta" = "diff_yellow"
"diff.minus" = "red"

"ui.background" = { }
"ui.cursor" = { fg = "fg", modifiers = ["reversed"] }
"ui.cursor.match" = { bg = "bg4" }
"ui.cursor.insert" = { fg = "black", bg = "grey" }
"ui.cursor.select" = { fg = "bg0", bg = "blue" }
"ui.selection" = { bg = "bg0" }
"ui.selection.primary" = { bg = "bg0" }
"ui.gutter" = { bg = "grey_dim" }
"ui.linenr" = { fg = "grey", bg = "grey_dim" }
"ui.linenr.selected" = { fg = "fg", bg = "grey_dim" }
"ui.cursorline.primary" = { bg = "bg1" }
"ui.statusline" = { fg = "fg", bg = "bg3" }
"ui.statusline.inactive" = { fg = "grey", bg = "bg1" }
"ui.statusline.normal" = { fg = "bg0", bg = "dark_yellow", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "bg0", bg = "blue", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "bg0", bg = "green", modifiers = ["bold"] }
"ui.popup" = { fg = "grey", bg = "bg2" }
"ui.window" = { fg = "grey", bg = "bg0" }
"ui.help" = { fg = "fg", bg = "bg1" }
"ui.text" = "fg"
"ui.text.focus" = "green"
"ui.menu" = { fg = "fg", bg = "bg2" }
"ui.menu.selected" = { fg = "bg0", bg = "green" }
"ui.virtual.whitespace" = "bg4" 
"ui.virtual.ruler" = { bg = "bg3" }
"ui.virtual.inlay-hint" = { fg = "grey_dim" }

info = { fg = 'green', bg = 'bg2' }
hint = { fg = 'blue', bg = 'bg2', modifiers = ['bold'] }
warning = { fg = 'diff_yellow', bg = 'bg2', modifiers = ['bold'] }
error = { fg = 'red', bg = 'bg2', modifiers = ['bold'] }

"diagnostic.info" = { underline = { style = "curl", color = "green" } }
"diagnostic.hint" = { underline = { style = "curl", color = "blue" } }
"diagnostic.warning" = { underline = { style = "curl", color = "diff_yellow" } }
"diagnostic.error" = { underline = { style = "curl", color = "red" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }



[palette]

black = "#181819"
bg_dim = "#222327"
bg0 = "#262626"
bg1 = "#33353f"
bg2 = "#363944"
bg3 = "#3b3e48"
bg4 = "#414550"
bg5 = "#444852"
bg_red = "#ff6077"
bg_green = "#a7df78"
bg_blue = "#85d3f2"

fg = "#e2e2e3"
diff_yellow = "#FFFD00"
dark_yellow = "#AFAF87"
grey_dim = "#303030"
grey = "#626262"
blue = "#5FD7FF"
yellow = "#AFAF87"
purple = "#AF5FFF"
red = "#D7005F"
green = "#87FF00"
orange = "#FF8700"
