[[language]]
name = "nix"
language-servers = [ "nixd" ]
formatter.command = "nixfmt"

[language-server.nixd]
command = "nixd"

[language-server.nixd.config]
nixpkgs.expr = "import (builtins.getFlake (\"git+file://\" + toString ./.)).inputs.nixpkgs { }"
options.nixos = "let nixpkgs = (builtins.getFlake (\"git+file://\" + toString ./.)).inputs.nixpkgs; in (import \"${nixpkgs}/nixos\" { configuration = import \"${nixpkgs}/nixos/modules/installer/netboot/netboot-base.nix\";}).options"

[[language]]
name = "markdown"
formatter = { command = "mdformat", args = ["--wrap", "80", "-"] }

[[language]]
name = "git-commit"
file-types = [{ glob = "COMMIT_EDITMSG" }, { glob = "MERGE_MSG" }, "pull"]

[[language]]
name = "bitbake"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py","vpy","pyi","py3","pyw",".pythonstartup",".pythonrc"]
shebangs = ["python"]
roots = [".", "pyproject.toml", "pyrightconfig.json"]
comment-token = "#"
language-servers = ["pyright", "ruff"]
indent = { tab-width = 4, unit = "    " }
auto-format = false

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
reportMissingTypeStubs = true

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
autoImportCompletions = true

[[grammar]]
name = "bash"
source = { git = "https://github.com/tree-sitter/tree-sitter-bash", rev = "0c46d792d54c536be5ff7eb18eb95c70fccdb232" }

[language-server.taplo.config]
# Workaround for nonsense of being nonfunctional outside git directories
# (https://github.com/helix-editor/helix/issues/3897#issuecomment-2361674437)
root_dir = [".git", "*.toml"]

# [language-server.rust-analyzer.config.check]
# command = "cargo clippy"
